Added flag for using a specific MAC address

diff --git a/changemac b/changemac
--- a/changemac
+++ b/changemac
@@ -10,18 +10,23 @@ Usage: ./changemac [flag]
   -h Show help info
   -r Use random MAC address
   -p Restore permanent MAC address
+  -s [MAC] specific MAC address
 EOF
 }
 
-rflag=true
+# Initialize flags
+rflag=false
+pflag=false
+sflag=false
 
-while getopts 'hrp' flag; do
+while getopts 'hrps:' flag; do
   case "${flag}" in
     h) usage
        exit 0 ;;
     r) rflag=true ;;
-    p) pflag=true 
-	   rflag=false ;; 
+    p) pflag=true ;; 
+    s) sflag=true
+	   parsed=$OPTARG ;;
     *) error "Unexpected option ${flag}" ;;
   esac
 done
@@ -31,6 +36,17 @@ echo "sudo access will be needed to run this script"
 
 curmac=$(ifconfig en0 | grep ether)
 oldmac=$(echo $curmac | sed "s/ether//")
+
+if [ "$sflag" = true ]
+then
+	if [[ "$parsed" =~ ^([0-9A-F]{2}:){5}[0-9A-F]{2}$ ]]
+	then
+		mac=$parsed 
+	else
+		echo "Invalid MAC address"
+		exit 1
+	fi
+fi
 
 if [ "$pflag" = true ] # Restore MAC
 then
@@ -48,6 +64,7 @@ if [ "$rflag" = true ] # Random MAC
 then
 	mac=$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')
 fi
+
 	
 # Disconnect from wifi and set new MAC 
 sudo ifconfig en0 down
